spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost/tasktracker}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
                action: create;
                create-target: create.sql;
                create-source: metadata;
db:
  entity:
    package: abdrayev.tasktracker.domain